name: artemis_fragments_issue
description: A new package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  artemis: ^7.1.1-beta.1
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^4.1.4
  test: ^1.17.10
